CREATE TABLE CLIENTES
(CPF VARCHAR (11),
NOME VARCHAR (100),
ENDEREÇO VARCHAR (150),
BAIRRO VARCHAR (50),
CIDADE VARCHAR (50),
ESTADO VARCHAR (50),
CEP VARCHAR (8),
IDADE SMALLINT,
SEXO VARCHAR (1),
LIMITE_CREDITO FLOAT,
VOLUME_CREDITO FLOAT,
PRIMEIRA_COMPRA BIT(1))

ALTER TABLE CLIENTES ADD PRIMARY KEY (CPF);

ALTER TABLE CLIENTES ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO CLIENTES (
CPF, NOME, ENDEREÇO, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO) VALUES (
'00985382908',
'Clodovilson Cunha',
'Rua dos marmelos, 674',
'Jardim dos abacates',
'Belo Vale das frutas',
'Minas Gerais',
'39468000',
48,
'M',
20000,
2000,
1,
'1974-01-31')

CREATE TABLE VENDEDORES 
(MATRICULA VARCHAR (5),
NOME VARCHAR (100),
PERCENTUAL_COMISSAO FLOAT)

ALTER TABLE VENDEDORES ADD PRIMARY KEY (MATRICULA)

CREATE TABLE PRODUTOS2
(CODIGO_DO_PRODUTO INT (5),
NOME_DO_PRODUTO VARCHAR (100),
EMBALAGEM VARCHAR (50),
TAMANHO FLOAT,
SABOR VARCHAR (100),
PRECO_DE_LISTA FLOAT)

DROP TABLE PRODUTOS2

DROP TABLE VENDEDORES

CREATE TABLE `sucos`.`produto` (
  `PRODUTO` VARCHAR(20) NULL,
  `NOME` VARCHAR(150) NULL,
  `EMBALAGEM` VARCHAR(50) NULL,
  `TAMANHO` VARCHAR(50) NULL,
  `SABOR` VARCHAR(50) NULL,
  `PRECO_LISTA` FLOAT NULL);

ALTER TABLE PRODUTO ADD PRIMARY KEY (PRODUTO)

use sucos;

insert into produto (
produto,
nome,
embalagem,
tamanho,
sabor,
preco_lista) values (
'1040107',
'Light - 350ml - Melancia',
'Lata',
'350 ml',
'Melancia',
4.56);

SELECT * FROM produto

CREATE TABLE VENDEDORES 
(MATRICULA VARCHAR (5),
NOME VARCHAR (100),
PERCENTUAL_COMISSAO FLOAT)

INSERT INTO VENDEDORES (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO) VALUES (
'00233',
'JOÃO GERALDO DA FONSECA',
10)

SELECT * FROM VENDEDORES

use sucos;

insert into produto (
produto,
nome,
embalagem,
tamanho,
sabor,
preco_lista) values (
'1037797',
'Clean - 2 Litros - Laranja',
'PET',
'2 Litros',
'Laranja',
16.01);

insert into produto (
produto,
nome,
embalagem,
tamanho,
sabor,
preco_lista) values (
'1000889',
'Sabor da Montanha - 700 ml - Uva',
'Garrafa',
'700 ml',
'Uva',
6.31);

insert into produto (
produto,
nome,
embalagem,
tamanho,
sabor,
preco_lista) values (
'1004327',
'Videira do Campo - 1,5 Litros - Melancia',
'PET',
'1,5 Litros',
'Melancia',
19.51);

SELECT * FROM produto

INSERT INTO VENDEDORES (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO) VALUES (
'00235',
'MARCIO ALMEIDA SILVA',
8)

INSERT INTO VENDEDORES (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO) VALUES (
'00236',
'CLAUDIA MORAIS',
8)

INSERT INTO produto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO produto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

USE sucos;

UPDATE PRODUTO SET EMBALAGEM = 'Lata', PRECO_LISTA = 2.46
WHERE PRODUTO = '544931';
UPDATE PRODUTO SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';

UPDATE VENDEDORES SET PERCENTUAL_COMISSAO = '11'
WHERE MATRICULA = '00236';
UPDATE VENDEDORES SET NOME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233';

DELETE FROM PRODUTOS WHERE PRODUTO = '1078680'

DELETE FROM VENDEDOR WHERE MATRICULA = '00233';

