SELECT * FROM itens_notas_fiscais;

SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE;

SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC; 

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS UNIT_VENDIDAS FROM itens_notas_fiscais GROUP BY CODIGO_DO_PRODUTO;

SELECT CODIGO_DO_PRODUTO, SUM(PRECO) AS VENDAS FROM itens_notas_fiscais GROUP BY CODIGO_DO_PRODUTO;

SELECT NUMERO, SUM(PRECO) AS VALOR_TOTAL_DA_NOTA FROM itens_notas_fiscais GROUP BY NUMERO;

SELECT CODIGO_DO_PRODUTO, COUNT(*) AS QUANTIDADE_TOTAL FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' GROUP BY CODIGO_DO_PRODUTO;

