SELECT * FROM notas_fiscais;

SELECT * FROM notas_fiscais WHERE DATA_VENDA = '2017-01-01';

SELECT * FROM notas_fiscais WHERE DATA_VENDA = '2017-01-01' LIMIT 10;

SELECT * FROM notas_fiscais ORDER BY MATRICULA;

SELECT * FROM notas_fiscais ORDER BY MATRICULA DESC;

SELECT * FROM notas_fiscais ORDER BY CPF, MATRICULA;

SELECT CPF, COUNT(*) AS QUANTIDADE_COMPRAS FROM notas_fiscais
WHERE YEAR (DATA_VENDA) = 2016 GROUP BY CPF HAVING COUNT(*)> 2000 ORDER BY CPF;
