SELECT LTRIM('       OLÁ') AS RESULTADO;

SELECT RTRIM('OLÁ            ') AS RESULTADO;

SELECT TRIM('          OLÁ            ') AS RESULTADO;

SELECT CONCAT('OLÁ!', ' ', 'TUDO', ' ', 'BEM', ' ', 'COM', ' ', 'VOCÊ?') AS RESULTADO;

SELECT UPPER('olá, tudo bem com você?') AS RESULTADO;

SELECT lower('OLÁ, TUDO BEM COM VOCÊ?') AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM COM VOCÊ?', 6) AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM COM VOCÊ?', 6 , 8) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;

SELECT CONCAT(NOME, ' (', CPF, '): ENDEREÇO: ', ENDERECO_1, ENDERECO_2, ', BAIRRO ', BAIRRO, ', ', CIDADE, ' - ', ESTADO, ', CEP ', CEP) 
AS RESULTADO FROM tabela_de_clientes;

SELECT CURDATE() AS DATAS_E_HORAS;

SELECT CURRENT_TIME() AS DATAS_E_HORAS;

SELECT current_timestamp() AS DATAS_E_HORAS;

SELECT YEAR(current_timestamp()) AS DATAS_E_HORAS;

SELECT MONTH(current_timestamp()) AS DATAS_E_HORAS;

SELECT DAY(current_timestamp()) AS DATAS_E_HORAS;

SELECT DAYNAME(current_timestamp()) AS DATAS_E_HORAS;

SELECT MONTHNAME(current_timestamp()) AS DATAS_E_HORAS;

SELECT DATEDIFF(current_timestamp(), '2020-03-20') AS DATAS_E_HORAS;

SELECT DATEDIFF(current_timestamp(), '2021-07-31') AS DATAS_E_HORAS;

SELECT DATEDIFF('2021-07-31', '2020-03-20') AS DATAS_E_HORAS;

SELECT DATEDIFF(current_timestamp(), '1998-04-30') AS DATAS_E_HORAS;

SELECT DATEDIFF('2021-07-31', '1998-04-30') AS DATAS_E_HORAS;

SELECT DATEDIFF(current_timestamp(), '1932-05-22') AS DATAS_E_HORAS;

SELECT DATE_SUB(current_timestamp(), INTERVAL 5 DAY) AS DATAS_E_HORAS;

SELECT current_timestamp() AS DIA_HOJE, DATE_SUB(current_timestamp(), INTERVAL 5 DAY) AS DATAS_E_HORAS;

SELECT DISTINCT DATA_VENDA, DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MÊS, year(DATA_VENDA)AS ANO 
FROM NOTAS_FISCAIS;

SELECT DATEDIFF(current_timestamp(), DATA_DE_NASCIMENTO) AS DATAS_E_HORAS FROM tabela_de_clientes;

SELECT NOME, timestampDIFF(YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS IDADE_ATUAL FROM tabela_de_clientes;

SELECT (23+((25-2)/2)*45) AS RESULT;

SELECT CEILING(12.34567898765456787654) AS RESULT;

SELECT ROUND(12.34567898765456787654) AS RESULT;

SELECT FLOOR(12.34567898765456787654) AS RESULT;

SELECT RAND() AS RESULT;

SELECT NUMERO, QUANTIDADE, PRECO, QUANTIDADE*PRECO AS FATURADO FROM ITENS_NOTAS_FISCAIS;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE*PRECO) AS FATURADO FROM ITENS_NOTAS_FISCAIS;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE*PRECO,2) AS FATURADO FROM ITENS_NOTAS_FISCAIS;

SELECT A.NUMERO, A.QUANTIDADE, A.PRECO, ROUND(A.QUANTIDADE*A.PRECO, 2) AS FATURAMENTO, B.IMPOSTO, ROUND(A.QUANTIDADE*A.PRECO*B.IMPOSTO, 2) AS TOTAL_IMPOSTO
FROM itens_notas_fiscais A INNER JOIN notas_fiscais B
ON A.NUMERO = B.NUMERO
GROUP BY A.NUMERO;

SELECT A.NUMERO, YEAR(B.DATA_VENDA), A.QUANTIDADE, A.PRECO, ROUND(A.QUANTIDADE*A.PRECO, 2) AS FATURAMENTO, B.IMPOSTO, ROUND(A.QUANTIDADE*A.PRECO*B.IMPOSTO, 2) AS TOTAL_IMPOSTO
FROM itens_notas_fiscais A INNER JOIN notas_fiscais B
ON A.NUMERO = B.NUMERO
WHERE YEAR(DATA_VENDA) =2016
GROUP BY A.NUMERO;

SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) AS IMPOSTO
FROM itens_notas_fiscais INF INNER JOIN notas_fiscais NF
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(DATA_VENDA) =2016
GROUP BY YEAR(DATA_VENDA);

SELECT current_timestamp() AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ', current_timestamp()) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),' %Y ')) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),' %y ')) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),'%d/%m/%y ')) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),'%d/%m/%Y ')) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),'%d/%c/%y ')) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),'%D/%M/%Y ')) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),'%d/%m/%Y, %W ')) AS RESULT;

SELECT CONCAT('O DIA DE HOJE É: ',
DATE_FORMAT(current_timestamp(),' %W, %d/%m/%Y, %r')) AS RESULT;

SELECT CONVERT (23.3, CHAR) AS RESULT;

SELECT SUBSTRING(CONVERT (23.3, CHAR),1,1) AS RESULT;

SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CAST(SUM(INF.QUANTIDADE * INF.preco) AS char (20))
 , ' no ano ', CAST(YEAR(NF.DATA_VENDA) AS char (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA)
